services:
  - type: web
    name: gmb-owner-finder
    env: python
    plan: free
    buildCommand: ./render/build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
