services:
  - type: web
    name: detect-owner-api
    env: python
    plan: free
    buildCommand: apt-get update && apt-get install -y build-essential python3-dev && PIP_CONFIG_FILE=pip.conf pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: gunicorn --bind 0.0.0.0:10000 app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
