services:
  - type: web
    name: detect-owner-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      python -c "import spacy; spacy.load('en_core_web_sm')"
    startCommand: flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
